const express=require("express")
const { userRegister, userLogin, sendOtpPassword, companySignup, resetPassword, userKyc, companyKyc, addLanguage, userEditProfile, verifyUser, updateLanguage } = require("../controllers/userControllers.js/register")
const upload = require("../middleware/multer")
const tokenAuthorisationUser = require("../middleware/userAuthentication")
const { createIdea, listBussinesIdeas, searchBussinessIdea, addBids, baseBidList, myBussinessIdea } = require("../controllers/userControllers.js/product")
const { pushNotification, PrivacyUser } = require("../controllers/userControllers.js/notification")
const { categoryList, subCategoryList } = require("../controllers/adminControllers/categoryController")
const router=express.Router()

router.post("/register-user",userRegister)
router.post("/register-company",companySignup)
router.post("/user-login",userLogin)
router.post("/send-otp",sendOtpPassword)
router.post("/reset-password",resetPassword)
router.post("/create-user_kyc/:id",upload.any(),userKyc)
router.post("/create-compny_kyc/:id",upload.any(),companyKyc)
router.post("/add-language",addLanguage)
router.post("/update-language/:id",updateLanguage)
router.post("/verify-user/:id",verifyUser)
router.post("/updated-profile/:id",tokenAuthorisationUser,upload.single("profile"),userEditProfile)
router.post("/create-idea",upload.any(),createIdea)
router.post("/list-bussiness-ideas",listBussinesIdeas)
router.post("/search-bussiness-ideas",searchBussinessIdea)
router.post("/push-notification",pushNotification)
router.post("/bids-add/:id",addBids)
router.post("/list-Bids/:id",baseBidList)
router.post("/my-bussiness-idea/:id",myBussinessIdea)
router.post("/category-list",categoryList)
router.post("/sub-category-list",subCategoryList)
router.post("/privacy-list",PrivacyUser)
module.exports=router